Feature/#7 refactor returnsgivenresult into proper extensions file
AndcultureCode/AndcultureCode.CSharp.Testing pull request #20
Opened 2020-10-06 17:24 UTC by ralphjmcintyre

#7 
- [x] Related GitHub issue(s) linked in PR description
- [x] Destination branch merged, built and tested with your changes
- [x] Code formatted and follows best practices and patterns
- [x] Code builds cleanly (no _additional_ warnings or errors)
- [-] Manually tested
- [x] Automated tests are passing
- [x] No _decreases_ in automated test coverage
- [-] Documentation updated (readme, docs, comments, etc.)
- [-] Localization: No hard-coded error messages in code files (_minimally_ in string constants)

2020-10-06 17:39 UTC, ralphjmcintyre commented
Ahh just saw the failed tests. I'll take a look at them.

2020-10-20 13:18 UTC, wintondeshong requested changes
@ralphjmcintyre thanks for adding this! In addition to resolving the tests, could you add a comment above the new method signature?

2020-10-20 13:18 UTC, wintondeshong commented on src/AndcultureCode.CSharp.Testing/Extensions/IResultReturnExtensions.cs
> +        public static IReturnsResult<T> ReturnsGivenResult<T, TResult>(this ISetup<T, IResult<TResult>> setup,
Please provide a comment above the method

2020-10-21 13:11 UTC, ralphjmcintyre commented on src/AndcultureCode.CSharp.Testing/Extensions/IResultReturnExtensions.cs
> +        public static IReturnsResult<T> ReturnsGivenResult<T, TResult>(this ISetup<T, IResult<TResult>> setup,
@wintondeshong I can do that. I'll try to resolve this this week!

2020-10-29 16:24 UTC, brandongregoryscott requested changes
Basic error comment looks fine 👍 Just one above `ReturnsGivenResult` and we should be good to go

2020-10-29 16:24 UTC, brandongregoryscott commented on src/AndcultureCode.CSharp.Testing/Extensions/IResultReturnExtensions.cs
> +        /// Returns basic error result.
I think this is fine 👍 thanks @ralphjmcintyre!

2020-10-29 16:28 UTC, brandongregoryscott commented on src/AndcultureCode.CSharp.Testing/Extensions/IResultReturnExtensions.cs
>      public static class IResultReturnExtensions
Just noticed this extension filename & class name are a little off. Based on the actual extensions, I think it would be more accurately named `ISetupExtensions` (the type being acted on as `this`). Additionally, we might want to flatten the namespace to `AndcultureCode.CSharp.Testing.Extensions` since we moved it around

2020-10-29 17:20 UTC, ralphjmcintyre commented
@brandongregoryscott I renamed the file and class and updated the namespace. Let me know if that's good! Thanks!

2020-11-01 01:16 UTC, brandongregoryscott approved these changes
Thanks for fixing this up, @ralphjmcintyre!

2020-11-02 13:18 UTC, merged

2021-04-12 12:30 UTC, brandongregoryscott commented
@all-contributors add @ralphjmcintyre for maintenance